

export const IMAGES = {
  vineoLogo: "/assets/images/vineo.svg" ,
  BANNER: '/images/banner.png',
  PROFILE_PLACEHOLDER: '/images/profile-placeholder.png',
  wine: '/images/piedra_negra_torrontés 3.svg',
  WINE_IMAGE_2: '/images/wine2.png',
  graph:"/assets/images/graph.svg" ,
  home:"/assets/images/home.svg",
  virtualcellar: "/assets/images/virtualcellar.svg",
  subscription:"/assets/images/subscription.svg",
  settings:"/assets/images/settings.svg",
  coins:"/assets/images/coins.svg",
  flag_America:"/assets/images/USA.svg",
  flag_Spain:"/assets/images/Spain.svg",
  WhatsApp:"/assets/images/whatsapp.svg",
  LandingImg:"/assets/images/landingimage1.svg",
  paperbg:"/assets/images/paper.png",
  learning:"/assets/images/learning.svg",
  winepack:"/assets/images/winebottles.svg",
 square:"/assets/images/squares.svg",
 graphdetails:"/assets/images/graphDt.svg",
 winedroping:"/assets/images/winedroping.svg",
 letter:"/assets/images/letter.svg",
 gif1:"/assets/images/gif1.gif",
 gif2:"/assets/images/gif2.gif",
 winegif:"/assets/images/winegif.gif",
 whatsappFooter:'/assets/images/whatsappFooter.svg',
 facebookFooter:'/assets/images/facebookFooter.svg',
 instaFooter:'/assets/images/instaFooter.svg',
 top:'/assets/images/top.svg',
 qn:'/assets/images/qn.svg'
  // Add more images as needed
};
